version: '3'
services:
  airflow-webserver:
    image: apache/airflow:2.6.3
    container_name: airflow-webserver
    command: standalone
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - PYTHONPATH=/opt/airflow/pdi/src  # Configura o PYTHONPATH para o diretório src
    volumes:
      - ./airflow/dags:/opt/airflow/dags  # DAGs
      - ./src:/opt/airflow/src            # Código fonte
    depends_on:
      - airflow-db

  airflow-db:
    image: postgres:13
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
